' ******************************************************************************
' swxJRNL.swj - journal recorded on 05/19/24 by Neeraj
' *****************************************************************************
Dim swApp As Object

Dim Part As Object
Dim boolstatus As Boolean
Dim longstatus As Long, longwarnings As Long

Sub main()

Set swApp = Application.SldWorks

swApp.ActivateDoc2 "Assembly", False, longstatus
Set Part = swApp.ActiveDoc
Set Part = swApp.ActiveDoc
Dim myModelView As Object
Set myModelView = Part.ActiveView
myModelView.FrameLeft = 0
myModelView.FrameTop = 0
Set myModelView = Part.ActiveView
myModelView.FrameState = swWindowState_e.swWindowMaximized
Set myModelView = Part.ActiveView
myModelView.FrameState = swWindowState_e.swWindowMaximized
boolstatus = Part.Extension.SelectByRay(0.4265723120171287519, 0.4300927509878818, 0.335039382665058838, -0.1580478097830905204, -0.2586964434855670292, -0.9529412573452191726, 0.004710931033789014788, 2, False, 0, 0)
boolstatus = Part.Extension.SelectByID2("", "FACE", 0.4265723120171287519, 0.4300927509878818, 0.335039382665058838, False, 0, Nothing, 0)
Part.ClearSelection2 True
boolstatus = Part.Extension.SelectByID2("4. four-1@Assembly", "COMPONENT", 0, 0, 0, False, 0, Nothing, 0)
Dim TransformData() As Double
ReDim TransformData(0 To 15) As Double
TransformData(0) = 0.9260916335659759024
TransformData(1) = -0.3756737861509885645
TransformData(2) = -0.03497845962994625135
TransformData(3) = -0.3754061098176065259
TransformData(4) = -0.9267519659536640475
TransformData(5) = 0.01417908010520266965
TransformData(6) = -0.03774306493534320545
TransformData(7) = 0
TransformData(8) = -0.9992874766799024755
TransformData(9) = 0.08121103374272328757
TransformData(10) = 0.6831525500042676668
TransformData(11) = 0.3320722616745100941
TransformData(12) = 1
TransformData(13) = 0
TransformData(14) = 0
TransformData(15) = 0
Dim TransformDataVariant As Variant
TransformDataVariant = TransformData
Dim swMathUtil As Object
Set swMathUtil = swApp.GetMathUtility()
Dim swTransform As Object
Set swTransform = swMathUtil.CreateTransform((TransformDataVariant))
Dim swComp As Object
Set swComp = Part.SelectionManager.GetSelectedObjectsComponent4(1, -1)
boolstatus = swComp.SetTransformAndSolve2(swTransform)
' MSGBOX
' Save changes to Assembly?

Set myModelView = Part.ActiveView
myModelView.FrameState = swWindowState_e.swWindowMaximized
Part.ClearSelection2 True
swApp.ExitApp
End Sub
